// <auto-generated />
using System;
using FamillyTree.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamillyTree.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608125436_anotherFieldsToPerson")]
    partial class anotherFieldsToPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FamillyTree.Models.Person", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrothersAndSisters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cousins")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dauthers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Father")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grandmas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grandpas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Husband")
                        .HasColumnType("TEXT");

                    b.Property<string>("LifeEvents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationY")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Mother")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfDeath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Wife")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("FamillyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
